// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioCV.Data;

#nullable disable

namespace PortfolioCV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116181534_AddSlugToModels")]
    partial class AddSlugToModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PortfolioCV.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("PortfolioCV.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Udemy",
                            Name = "Asp.Net Core 8.0 ile Sıfırdan İleri Seviye Web Geliştirme",
                            Order = 1,
                            Slug = ""
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2017, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Udemy",
                            Name = "Komple Uygulamalı Web Geliştirme Eğitimi",
                            Order = 2,
                            Slug = ""
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Issuer = "Udemy",
                            Name = "Python ile Sıfırdan İleri Seviye Programlama",
                            Order = 3,
                            Slug = ""
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("PortfolioCV.Models.CvReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("References");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Vakıf Katılım",
                            Email = "",
                            Name = "Nebi Erdal Akkabak",
                            Order = 1,
                            Phone = "+90 (537) 363 18 15",
                            Position = "Bireysel Portföy Müdürü",
                            Slug = ""
                        },
                        new
                        {
                            Id = 2,
                            Company = "ODELLO OTOMOTİV",
                            Email = "m.fatihyilmaz@outlook.com",
                            Name = "Fatih Yılmaz",
                            Order = 2,
                            Phone = "+90 (539) 947 47 59",
                            Position = "Kalıphane Mühendisi",
                            Slug = ""
                        },
                        new
                        {
                            Id = 3,
                            Company = "Softtech A.Ş.",
                            Email = "",
                            Name = "İsa Demir",
                            Order = 3,
                            Phone = "+90 (535) 027 29 47",
                            Position = "Ürün Mimarı",
                            Slug = ""
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Faculty")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Grade")
                        .HasColumnType("REAL");

                    b.Property<string>("GradeSystem")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContinuing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeachingType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Mekatronik Mühendisliği",
                            EducationType = "Lisans",
                            EndDate = new DateTime(2017, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Teknoloji Fakültesi",
                            Grade = 2.9100000000000001,
                            GradeSystem = "4",
                            IsContinuing = false,
                            Order = 1,
                            School = "Karabük Üniversitesi",
                            Slug = "",
                            StartDate = new DateTime(2012, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Department = "Bilgisayar Programcılığı",
                            EducationType = "Ön Lisans",
                            EndDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Açıköğretim Fakültesi",
                            Grade = 2.6699999999999999,
                            GradeSystem = "4",
                            IsContinuing = false,
                            Order = 2,
                            School = "Anadolu Üniversitesi",
                            Slug = "",
                            StartDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Department = "İş Sağlığı ve Güvenliği",
                            EducationType = "Ön Lisans",
                            Faculty = "Açıköğretim Fakültesi",
                            IsContinuing = true,
                            Order = 3,
                            School = "Atatürk Üniversitesi",
                            Slug = "",
                            StartDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EducationType = "Lise",
                            EndDate = new DateTime(2011, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContinuing = false,
                            Order = 4,
                            School = "Faruk Nafiz Çamlıbel Anadolu İmam Hatip Lisesi",
                            Slug = "",
                            StartDate = new DateTime(2007, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EducationType = "İlköğretim",
                            EndDate = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsContinuing = false,
                            Order = 5,
                            School = "Darüşşafaka Eğitim Kurumları",
                            Slug = "",
                            StartDate = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentlyWorking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul",
                            CompanyName = "Bireysel",
                            Department = "Freelance",
                            Industry = "Freelance",
                            IsCurrentlyWorking = true,
                            Order = 1,
                            Position = "Proje Geliştirici",
                            Slug = "",
                            StartDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "İstanbul",
                            CompanyName = "PYS Geliştirmesi",
                            Department = "Freelance",
                            EndDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Freelance",
                            IsCurrentlyWorking = false,
                            Order = 2,
                            Position = "Freelance Geliştirici",
                            Slug = "",
                            StartDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "İstanbul",
                            CompanyName = "E-Ticaret Sitesi",
                            Department = "Freelance",
                            EndDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Freelance",
                            IsCurrentlyWorking = false,
                            Order = 3,
                            Position = "Web Geliştirici",
                            Slug = "",
                            StartDate = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kocaeli",
                            CompanyName = "Tork Mühendislik Asansör",
                            Department = "Mühendislik",
                            EndDate = new DateTime(2017, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Asansör",
                            IsCurrentlyWorking = false,
                            Order = 5,
                            Position = "Stajyer Mühendis",
                            Slug = "",
                            StartDate = new DateTime(2017, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "İstanbul",
                            CompanyName = "Geta Grup Asansör",
                            Department = "AR-GE",
                            EndDate = new DateTime(2017, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Industry = "Asansör",
                            IsCurrentlyWorking = false,
                            Order = 4,
                            Position = "Stajyer Mühendis",
                            Slug = "",
                            StartDate = new DateTime(2017, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "B2",
                            Name = "İngilizce",
                            Order = 1,
                            Slug = ""
                        },
                        new
                        {
                            Id = 2,
                            Level = "A1",
                            Name = "Fransızca",
                            Order = 2,
                            Slug = ""
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrivingLicenseClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDrivingLicense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MilitaryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Mekatronik mühendisliği mezunu, yazılım geliştirme tutkunu bir profesyonelim. .NET Core, C# ve modern web teknolojileri üzerine uzmanlaşmaktayım.",
                            Address = "Pendik / İstanbul",
                            DrivingLicenseClass = "B",
                            Email = "veysel.mut@hotmail.com",
                            FullName = "Veysel Mut",
                            Gender = "Erkek",
                            HasDrivingLicense = true,
                            MilitaryStatus = "Yapıldı",
                            Phone = "+90 (531) 229 74 05",
                            Title = "Mekatronik Mühendisi / Yazılım Geliştirici"
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tasks")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ASP.NET Core 8.0 MVC ile geliştirilmiş modern portföy ve CV sitesi",
                            Name = ".NET Core Tabanlı Bireysel Portföy Sitesi",
                            Order = 1,
                            Slug = "",
                            Tasks = "Frontend tasarım\nBackend geliştirme\nVeritabanı yönetimi\nAdmin panel entegrasyonu",
                            Url = "https://github.com/veyselmut/PortfolioCV"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kapsamlı e-ticaret platformu",
                            Name = "ASP.NET 6 Tabanlı E-Ticaret Sitesi",
                            Order = 2,
                            Slug = "",
                            Tasks = "Ürün yönetimi\nSepet sistemi\nÖdeme entegrasyonu"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kurumsal personel takip ve yönetim sistemi",
                            Name = "Personel Yönetim Sistemi (PYS)",
                            Order = 3,
                            Slug = "",
                            Tasks = "Personel kayıt\nİzin yönetimi\nRaporlama"
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("PortfolioCV.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 85,
                            Name = "C# / ASP.NET Core",
                            Order = 1,
                            Slug = ""
                        },
                        new
                        {
                            Id = 2,
                            Level = 80,
                            Name = "MS SQL Server",
                            Order = 2,
                            Slug = ""
                        },
                        new
                        {
                            Id = 3,
                            Level = 85,
                            Name = "Entity Framework Core",
                            Order = 3,
                            Slug = ""
                        },
                        new
                        {
                            Id = 4,
                            Level = 75,
                            Name = "HTML / CSS / JS",
                            Order = 4,
                            Slug = ""
                        },
                        new
                        {
                            Id = 5,
                            Level = 70,
                            Name = "Git / Docker",
                            Order = 5,
                            Slug = ""
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Github")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Twitter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Youtube")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Github = "https://github.com/veyselmut",
                            Instagram = "https://instagram.com/veyselmut",
                            LinkedIn = "https://linkedin.com/in/veyselmut",
                            Twitter = "https://x.com/veyselmut",
                            Youtube = "https://youtube.com/veyselmut"
                        });
                });

            modelBuilder.Entity("PortfolioCV.Models.WelcomeMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WelcomeMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = ".NET Teknolojileri ve Modern Web Çözümleri üzerine uzmanlaşmış dijital portfolyoma hoş geldiniz.",
                            Subtitle = "Mekatronik Mühendisi & Yazılım Geliştirici",
                            Title = "Merhaba, Ben Veysel Mut!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
